import { builder } from "../../builder";
import {
  ProposalStatusEnum,
  ProposalSideEnum,
  OrderEntryTypeEnum,
} from "../../types/enums";

builder.objectType("Proposal", {
  description: "A trade proposal generated by a bot, pending user approval",
  fields: (t) => ({
    id: t.exposeID("id"),

    // bot resolved via DataLoader — avoids N+1 when listing proposals
    bot: t.field({
      type: "Bot",
      resolve: async (proposal, _args, ctx) =>
        ctx.loaders.botById.load(String(proposal.bot_id)),
    }),

    symbol: t.exposeString("symbol"),

    side: t.field({
      type: ProposalSideEnum,
      resolve: (p) => p.side,
    }),

    qty: t.field({
      type: "Decimal",
      resolve: (p) => p.qty.toString(),
    }),

    entryType: t.field({
      type: OrderEntryTypeEnum,
      resolve: (p) => p.entry_type,
    }),

    // Price fields — nullable depending on entry_type
    limitPrice: t.field({
      type: "Decimal",
      nullable: true,
      resolve: (p) => p.limit_price?.toString() ?? null,
    }),

    stopPrice: t.field({
      type: "Decimal",
      nullable: true,
      resolve: (p) => p.stop_price?.toString() ?? null,
    }),

    targetPrice: t.field({
      type: "Decimal",
      nullable: true,
      resolve: (p) => p.target_price?.toString() ?? null,
    }),

    // Confidence score from the rule engine (0.00–1.00)
    confidence: t.field({
      type: "Decimal",
      resolve: (p) => p.confidence.toString(),
    }),

    rationaleText: t.string({
      nullable: true,
      resolve: (p) => p.rationale_text ?? null,
    }),

    status: t.field({
      type: ProposalStatusEnum,
      resolve: (p) => p.status,
    }),

    // min_hold_until enforces PDT avoidance at the data layer
    minHoldUntil: t.field({
      type: "DateTime",
      resolve: (p) => new Date(p.min_hold_until),
    }),

    expiresAt: t.field({
      type: "DateTime",
      resolve: (p) => new Date(p.expires_at),
    }),

    createdAt: t.field({
      type: "DateTime",
      resolve: (p) => new Date(p.created_at),
    }),
  }),
});
